### ISSUE TITLE
possibly unreliable cache, race conditions

### ISSUE THREAD

**Issue by ghost** [Web-Prolog/swi-web-prolog-lite#4]
I don’t think your cache will work correctly. There are race conditions in your code. Like here (from master/node.pl, line 178):

```
once(findnsols(Mtop, Pid0, with_mutex(cache, cache(_, _, Pid0)), Pids)),
with_mutex(cache, maplist(kill_thread, Pids)
```
Between the first goal and the second goal, another query might lookup the cache/3 and use the Pid, nevertheless the Pid gets killed.

**Comment by torbjornlager** [comment]
Thanks! Fixed with latest commit.
